### PR TITLE
[FIX] SF Sneakpeek when app timer is enabled for session timeout

### LINKED ISSUE #978: [SF] Sneak Peak not working when we use App Timer for Idle Session Timeout

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/978

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you resolve the conflict here and get up to date with master please?  thanks......

**Comment by Shailesh351** [comment]
@ear-dev This PR is no more needed as this issue is fixed along with https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/47.

Sneak peek is now working with AppTimer. However, after merging 47 I noticed, salesforce agent name is not showing up in the widget.

**Comment by ear-dev** [comment]
@Shailesh351 are you sure that the agent name is not showing up in the widget for you?  Looks like it is there for me......image

**Comment by Shailesh351** [comment]
@ear-dev I tested again and now it's working. Maybe my local setup was in a bad state. Sorry about that. Thanks!

**Pull request closed without merging**
