### PR TITLE
Add Agent Typing Indicator

### LINKED ISSUE #6: [FEATURE] Agent typing Indicators
< Requires upcoming app-engine 1.17.0* with UIKit>
- [ ] Set Typing Indicator ON when Live Agent Starts typing. Stop it when a message arrives
- [ ] Sending 'ChasitorTyping' event when Live Chat user starts typing.

*im guessing the name

### PR DESCRIPTION
**Pull request by Shailesh351**
### Changes
When agent is typing from salesforce console, show typing indicator on LiveChat widget that agent is typing.

### Demo
https://youtu.be/bZjp3EamZ90

### Depends On 
https://github.com/RocketChat/Rocket.Chat/pull/19228 which will be part of next RC release 3.8.0 https://github.com/RocketChat/Rocket.Chat/milestone/214

### CODE REVIEW

**Comment by PrajvalRaval** [comment]
@Shailesh351 I am facing this issue while doing a deploy of the app:

```
prajvalraval@Prajvals-MacBook-Pro Apps.Salesforce.LiveAgent-sb_agent_typing % rc-apps deploy --username prajval.admin --password 123456 --url http://localhost:3000
packaging your app... packaged!
deploying your app... !
Error: Deployment error: Invalid App package. Could not find the classFile (SalesforceLiveAgentApp.js) file.
    at Deploy.asyncSubmitData (/usr/local/lib/node_modules/@rocket.chat/apps-cli/lib/commands/deploy.js:100:19)
```

I tried uploading the dist file directly but still facing the same issue.

**Comment by Shailesh351** [comment]
@PrajvalRaval which version of server you are running?

I have tested with cherry picking commits form upstream PR.

And also there are some changes going on for removing ts compiler for appa may be that can be the issue.

**Comment by PrajvalRaval** [comment]
> @PrajvalRaval which version of server you are running?
> 
> I have tested with cherry picking commits form upstream PR.
> 
> And also there are some changes going on for removing ts compiler for appa may be that can be the issue.

Using this one -> https://github.com/RocketChat/Rocket.Chat/releases/tag/3.8.0-rc.0

**Comment by Shailesh351** [comment]
@PrajvalRaval For now to test this one you can cherry-pick changes from https://github.com/RocketChat/Rocket.Chat/pull/19228 on our develop_pwa branch.


There is major change in app compilation and packaging process from upstream. We will need to first merge upstream catchup PRs in Apps-Engine and RC Server.
https://github.com/RocketChat/Rocket.Chat/pull/18687
https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/307
https://github.com/RocketChat/Rocket.Chat.Apps-compiler
We will also need latest version(1.7.1) for Apps-CLI https://github.com/RocketChat/Rocket.Chat.Apps-cli/pull/85 https://github.com/RocketChat/Rocket.Chat.Apps-cli/releases/tag/v1.7.1

**Comment by PrajvalRaval** [comment]
> @PrajvalRaval For now to test this one you can cherry-pick changes from [RocketChat/Rocket.Chat#19228](https://github.com/RocketChat/Rocket.Chat/pull/19228) on our develop_pwa branch.
> 
> There is major change in app compilation and packaging process from upstream. We will need to first merge upstream catchup PRs in Apps-Engine and RC Server.
> [RocketChat/Rocket.Chat#18687](https://github.com/RocketChat/Rocket.Chat/pull/18687)
> [RocketChat/Rocket.Chat.Apps-engine#307](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/307)
> https://github.com/RocketChat/Rocket.Chat.Apps-compiler
> We will also need latest version(1.7.1) for Apps-CLI [RocketChat/Rocket.Chat.Apps-cli#85](https://github.com/RocketChat/Rocket.Chat.Apps-cli/pull/85) https://github.com/RocketChat/Rocket.Chat.Apps-cli/releases/tag/v1.7.1

I see... These are a lot of changes so let's wait for the releases, I am sure they will be out in a few days, then we can sync them into our repos. Let's keep this PR review pending till that. 👍

**Comment by Shailesh351** [comment]
> I see... These are a lot of changes so let's wait for the releases, I am sure they will be out in a few days, then we can sync them into our repos. Let's keep this PR review pending till that. 👍

Cool!!

**Comment by ear-dev** [comment]
@Shailesh351 will we be able to merge this one after we merge the new Rocket.Chat catchup to 3.8.0?

**Comment by Shailesh351** [comment]
Yupp @ear-dev

**Pull request merged**
