### PR TITLE
Standardize formatting, update linter

### PR DESCRIPTION
**Pull request by csmith14**
- Removes `tslint` from `devDependencies`, as [tslint was deprecated in 2019](https://www.infoq.com/news/2019/02/tslint-deprecated-eslint/#:~:text=Palantir%2C%20the%20creators%20of%20TSLint,TSLint%20team%20have%20been%20ongoing.), and replaces it with the family of `@typescript-eslint` packages.
- Removes `tslint` config
- Adds `.eslintrc.json` configuration to match the rules of prior `tslint` config
- Adds a `.prettierrc` configuration to match the formatting rules of prior `tslint` config
- Adds `lint:fix` and `format` npm-scripts to `package.json`
- Applies new linter and formatter to all `*.ts` source files

### CODE REVIEW

**Review by Shailesh351 — APPROVED** [review]
This is great @csmith14 Thanks!

**Comment by ear-dev** [comment]
Please cross check with the rules that are in the Rocket.Chat repo.  Those are the rules that are standardized across the other RC repos.

**Comment by ear-dev** [comment]
Thanks @csmith14 ....  @bhardwajaditya can you take one last look at this PR and also this one please:  https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/64.  We'll want to run a few tests on them both merged together locally just to confirm please that it all works as expected.  Thanks!

**Review by bhardwajaditya — APPROVED** [review]
I have gone through the changes, all looks good to me

**Comment by ear-dev** [comment]
Thanks @bhardwajaditya ........  @csmith14 please go ahead and merge these two PRs....

**Pull request merged**
