### PR TITLE
[FIX] Fixed Messages and Added SNS Events for Closing Session after Escalation.

### LINKED ISSUE #1278: [BUG] [Chat End Logging] Fix "Conversation closed:" logging as seen in a chat session transcript for escalated sessions
Currently the "Conversation closed" message is not always accurate.  

For example, in an escalated session all Conversation closed messages show "Chat ended by visitor", even if the chat was actually closed by the agent, or timed out. 
https://github.com/WideChat/Apps.Salesforce.LiveAgent/blob/master/helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/HandleEndChatCallback.ts#L62

We need to properly define all the reasons while closing rooom. visitor, agent, session expired etc.  We should verify for both escalated and non escalated sessions. 

As a side note: our SNS event logging for chat closed needs to be accurate as well...

### PR DESCRIPTION
**Pull request by Shailesh351**
Created for testing

Closes https://github.com/WideChat/Rocket.Chat/issues/1278

Clone of https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/75
Reverts WideChat/Apps.Salesforce.LiveAgent#83

### CODE REVIEW

**Comment by Shailesh351** [comment]
The issues found in the main PR are
- some events are being sent multiple times. In this file `handlers/InitiateSalesforceSessionHandler.ts` we are calling `logHandoverFailure` and `checkAgentStatusCallbackError` which internally send SNS event
- when we receive `response.statusCode === 204` from the API it's handled differently in different places. At one place we are sending event `CHAT_CLOSED_DUE_TO_EMPTY_MESSAGE_FROM_LIVEAGENT` and at other `CHAT_CLOSED_LIVEAGENT_SESSION_EXPIRED`

**Review by AlexanderKanakis — APPROVED** [review]

**Comment by ear-dev** [comment]
Thanks guys.... I will test

**Review by ear-dev — APPROVED** [review]
@Shailesh351 I tested this in preprod and it looks good.  If you're good to go, I will merge. Thanks!

**Comment by ear-dev** [comment]
@Shailesh351 what is this?   {"close_method": "expired_session"} <- SF.app

I'm seeing a bunch of these show up during the regression tests with the testbot.  I think it might be causing our close-session-method chart to not match with sessions-started.  Thanks.

**Comment by Shailesh351** [comment]
@ear-dev We are sending close_method: "expired_session" when the chat is expired from the salesforce side. That is when we receive response code 403 from the salesforce

**Comment by ear-dev** [comment]
> @ear-dev We are sending close_method: "expired_session" when the chat is expired from the salesforce side. That is when we receive response code 403 from the salesforce

@Shailesh351 I'm seeing both closed_method events, 'expired_session' and 'timeout' for every timeout.  Maybe we should not send an event for expired_session since we are already catching the timeout?

**Comment by Shailesh351** [comment]
> @Shailesh351 I'm seeing both closed_method events, 'expired_session' and 'timeout' for every timeout. Maybe we should not send an event for expired_session since we are already catching the timeout?

@ear-dev Ohh... That's the issue. I will look into it 👍

**Comment by ear-dev** [comment]
> > @Shailesh351 I'm seeing both closed_method events, 'expired_session' and 'timeout' for every timeout. Maybe we should not send an event for expired_session since we are already catching the timeout?
> 
> @ear-dev Ohh... That's the issue. I will look into it 👍

@Shailesh351 I created a new story to track and come up with a fix:  https://github.com/WideChat/Rocket.Chat/issues/1331

**Pull request merged**
