### PR TITLE
Use updatePersistentData instead of updateByAssociation

### PR DESCRIPTION
**Pull request by csmith14**
Addresses the changes requested post-merge on [PR#62](https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/62)

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you take a look at this one when you have a chance please?  Thanks...

**Review by Shailesh351 — COMMENTED** [review]
@csmith14 These changes look good to me. 

However, while deploying the app, I am seeing below error
```
   Starting App Deployment to Server

   Getting Server Info... ✓
   Packaging the app... ✖
 ›   Error:    ⟿  Failed to resolve module: ../helperFunctions/subscribeHelpers/SalesforceAgentAssignedHelpers/SubsribeToLiveAgentHelper
```

I think you missed renaming one of the imports in your recent PR for fixing spelling issues?

**Comment by ear-dev** [comment]
@csmith14 can you fix the conflict please?

**Comment by ear-dev** [comment]
@Shailesh351 can you approve this if it's ready please?

**Review by Shailesh351 — COMMENTED** [review]
LGTM

**Review by Shailesh351 — APPROVED** [review]

**Pull request merged**
