### PR TITLE
[EXTEND] Added customField message that specifies timeout handler app/widget

### PR DESCRIPTION
**Pull request by AlexanderKanakis**

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 or @bhardwajaditya can one of you review this PR please?  Thanks......

**Comment by bhardwajaditya** [comment]
@ear-dev these changes are tested or they require testing as well?

**Comment by ear-dev** [comment]
@bhardwajaditya if you can test as well that would be great.  thanks.

**Comment by ear-dev** [comment]
@AlexanderKanakis seems like you missed including the taskScheduler in this PR.... thanks.

**Comment by bhardwajaditya** [comment]
@ear-dev I tested these changes, I can see the sneak peek with the timer but post chat end the chat is ended for salesforce agent but for the visitor the close chat banner is not available and it still allows to send messages

**Comment by ear-dev** [comment]
@AlexanderKanakis I am seeing the same issue that @bhardwajaditya has flagged in this PR......  I commented on it in the corresponding livechat PR......  Can you fix please?  Thanks.

**Pull request closed without merging**
