### PR TITLE
[FIX] ChasitorTyping/ChasitorNotTyping data not sent when sneakpeek is active

### PR DESCRIPTION
**Pull request by csmith14**

### CODE REVIEW

**Comment by ear-dev** [comment]
@Shailesh351 can you review please?  Thanks...

**Comment by ear-dev** [comment]
@csmith14 I deployed this to the dev server but am not seeing sneak peak or typing indicator.

**Comment by csmith14** [comment]
@ear-dev it's hard for me to respond to what you're seeing on your end, however I have tested this against the simulator to confirm that the app is now sending requests to both the `/Chasitor/ChasitorTyping` and `/Chasitor/ChasitorNotTyping` endpoints along with the `/Chasitor/ChasitorSneakPeek` endpoint during conversations.

It is possible that there is a separate issue that is causing sneak-peek and/or typing data to not be visible on the SF side in specific environments.

This fix was intended to resolve the issue of typing/not-typing data being unavailable when sneak-peek is active.

**Comment by ear-dev** [comment]
@csmith14 So this did work against the emulator just now when you and i did it together...  just putting a note here that the behavior is flaky, and it seems like we still have that bug in our code where sneak peek sometimes does not work.  I'll create a new story for that......  @Shailesh351 are you still seeing that sneak peek is working for you in all scenarios?

**Review by Shailesh351 — COMMENTED** [review]
@csmith14 Why do we need to send `ChasitorTyping/ChasitorNotTyping` when we are already sending `ChasitorSneakPeek`

When I tried Salesforce Chat Button, It was only sending `ChasitorSneakPeek` when SneakPeak was enabled.

Screenshot 2022-05-17 at 3 11 12 PM

Also, if we send `ChasitorTyping/ChasitorNotTyping`, it overrides previously sent text to `ChasitorSneakPeek` and just shows dots `...` in the salesforce chat.

One more thing, you are using `await Promise.all(requestPromises);` which will wait for both the promises to resolve. And it's possible that `ChasitorTyping/ChasitorNotTyping` resolves after `ChasitorSneakPeek`, which will override SneakPeak text.

So I think the way it is implemented currently is correct, unless you are able to reproduce the flaky behavior (We all are trying to reproduce it 🙂 ).

@ear-dev Yes In my local testing it was working on all the platforms. If it's flaky for you can you try to get more info like, does it happen on a specific server/env, does it happen with only specific steps?

**Comment by ear-dev** [comment]
OK, I think we do not need this PR.

**Pull request closed without merging**
