### PR TITLE
[FIX] agentEndedChat Flag based on reason received in ChatEnded

### LINKED ISSUE #1282: [BUG][SF] agentEndedFlag is true when chat ended by visitor
When chat is ended by Salesforce Agent, it sets a flag in customFields `agentEndedFlag` to true.
But currently, it is also setting a flag in the case when the visitor ends the chat, which is misleading.

For now to differentiate chat ended by visitor and agent we can check `Conversation closed:` reason in RC .
It shows `Chat closed by visitor..` when the agent closes the chat.
It shows `Closed by visitor.` when the visitor closes the chat
We are going to fix this confusion separately in https://github.com/WideChat/Rocket.Chat/issues/1278

FYI @ear-dev

### PR DESCRIPTION
**Pull request by Shailesh351**
Closes https://github.com/WideChat/Rocket.Chat/issues/1282

### CODE REVIEW

**Comment by AlexanderKanakis** [comment]
We have some lint errors.

**Review by AlexanderKanakis — APPROVED** [review]
LGTM

**Comment by ear-dev** [comment]
@Shailesh351 To clarify for me please...... This PR fixes the issue where our 'agentEndedChat' flag was not correct because it was always being set to true?  But our messaging in the transcript window will still show either "Chat closed by visitor" or "Closed by visitor"........  and we will fix that in the other PR?  thanks

**Comment by Shailesh351** [comment]
> @Shailesh351 To clarify for me please...... This PR fixes the issue where our 'agentEndedChat' flag was not correct because it was always being set to true?  But our messaging in the transcript window will still show either "Chat closed by visitor" or "Closed by visitor"........  and we will fix that in the other PR?  thanks

Yes, exactly....

**Comment by ear-dev** [comment]
> > @Shailesh351 To clarify for me please...... This PR fixes the issue where our 'agentEndedChat' flag was not correct because it was always being set to true?  But our messaging in the transcript window will still show either "Chat closed by visitor" or "Closed by visitor"........  and we will fix that in the other PR?  thanks
> 
> Yes, exactly....

ok, cool..... thanks

**Pull request merged**
