### PR TITLE
[FIX] Send Close Chat Message to Livechat User

### LINKED ISSUE #1298: [BUG] [Duplicate of 1297] - Conversation closed message contains the a DF.config value for "close_chat_message"
The DF.config value for "close_chat_message" should appear in the transcript window.  

Our bug is that when we hit the "invalid department" error during escalation,  it is currently showing up in the "Conversaion closed:" system messages.

### PR DESCRIPTION
**Pull request by AlexanderKanakis**
Solves: Solves: https://github.com/WideChat/Rocket.Chat/issues/1298 and https://github.com/WideChat/Rocket.Chat/issues/1297

Please merge after: https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/75

### CODE REVIEW

**Review by Shailesh351 — COMMENTED** [review]
Review comments are added in https://github.com/WideChat/Apps.Salesforce.LiveAgent/pull/75

**Comment by ear-dev** [comment]
@AlexanderKanakis please merge these changes into PR 75, and close this PR.  It's going to be easier to look at a single SF set of changes.

**Comment by AlexanderKanakis** [comment]
Merged #78 to #75 . We can close this.

**Comment by ear-dev** [comment]
Thanks.

**Pull request closed without merging**
